-- MySQL Script generated by MySQL Workbench
-- mié 26 jul 2017 00:34:01 PET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ii_admision_unsa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ii_admision_unsa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ii_admision_unsa` DEFAULT CHARACTER SET utf8 ;
USE `ii_admision_unsa` ;

-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Cargo_Proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Cargo_Proceso` (
  `idCargo_Proceso` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Vigente` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idCargo_Proceso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Cargo_UNSA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Cargo_UNSA` (
  `idCargo_UNSA` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Vigente` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idCargo_UNSA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Participante` (
  `DNI` INT NOT NULL,
  `Apellidos` VARCHAR(45) NULL DEFAULT NULL,
  `Nombres` VARCHAR(45) NULL DEFAULT NULL,
  `Correo` VARCHAR(45) NULL DEFAULT NULL,
  `CUI` INT NULL DEFAULT NULL,
  `Numero_de_participaciones` INT NOT NULL,
  `Tiene_Cargo_Proceso` TINYINT(1) NOT NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Tipo_Proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Tipo_Proceso` (
  `idTipo_Proceso` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Lema` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipo_Proceso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Proceso` (
  `idProceso` INT NOT NULL,
  `Anho` INT NULL DEFAULT NULL,
  `Inicio` DATETIME NULL DEFAULT NULL,
  `Fin` DATETIME NULL DEFAULT NULL,
  `idTipo_Proceso` INT NOT NULL,
  `Fase` INT NOT NULL,
  `Nro_total_de_preguntas` INT NULL,
  `Nro_hecho_de_preguntas` INT NULL,
  `Dia_de_examen_1` DATETIME NULL,
  `Dia_de_examen_2` DATETIME NULL,
  `Dia_de_examen_3` DATETIME NULL,
  PRIMARY KEY (`idProceso`),
  INDEX `fk_Proceso_1_idx` (`idTipo_Proceso` ASC),
  CONSTRAINT `fk_Proceso_1`
    FOREIGN KEY (`idTipo_Proceso`)
    REFERENCES `ii_admision_unsa`.`Tipo_Proceso` (`idTipo_Proceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Aula` (
  `idAula` INT NOT NULL,
  `Pabellon` VARCHAR(45) NULL,
  `Capacidad` VARCHAR(45) NULL,
  `Ubicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idAula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`ProcesoXParticipanteXCargo_ProcesoXCargo_UNSA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`ProcesoXParticipanteXCargo_ProcesoXCargo_UNSA` (
  `idProcesoXParticipanteXCargo_ProcesoXCargo_UNSA` INT NOT NULL AUTO_INCREMENT,
  `idProceso` INT NULL,
  `DNI` INT NULL,
  `idCargo_Proceso` INT NULL,
  `idCargo_UNSA` INT NULL,
  `idAula` INT NULL,
  `Hora_inicio` TIME NULL,
  `Hora_fin` TIME NULL,
  PRIMARY KEY (`idProcesoXParticipanteXCargo_ProcesoXCargo_UNSA`),
  INDEX `fk_ProcesoXParticipanteXCargo_ProcesoXCargo_UNSA_1_idx` (`idProceso` ASC),
  INDEX `fk_ProcesoXParticipanteXCargo_ProcesoXCargo_UNSA_2_idx` (`DNI` ASC),
  INDEX `fk_ProcesoXParticipanteXCargo_ProcesoXCargo_UNSA_3_idx` (`idCargo_Proceso` ASC),
  INDEX `fk_ProcesoXParticipanteXCargo_ProcesoXCargo_UNSA_4_idx` (`idCargo_UNSA` ASC),
  INDEX `fk_ProcesoXParticipanteXCargo_ProcesoXCargo_UNSA_5_idx` (`idAula` ASC),
  CONSTRAINT `fk_ProcesoXParticipanteXCargo_ProcesoXCargo_UNSA_1`
    FOREIGN KEY (`idProceso`)
    REFERENCES `ii_admision_unsa`.`Proceso` (`idProceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProcesoXParticipanteXCargo_ProcesoXCargo_UNSA_2`
    FOREIGN KEY (`DNI`)
    REFERENCES `ii_admision_unsa`.`Participante` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProcesoXParticipanteXCargo_ProcesoXCargo_UNSA_3`
    FOREIGN KEY (`idCargo_Proceso`)
    REFERENCES `ii_admision_unsa`.`Cargo_Proceso` (`idCargo_Proceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProcesoXParticipanteXCargo_ProcesoXCargo_UNSA_4`
    FOREIGN KEY (`idCargo_UNSA`)
    REFERENCES `ii_admision_unsa`.`Cargo_UNSA` (`idCargo_UNSA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProcesoXParticipanteXCargo_ProcesoXCargo_UNSA_5`
    FOREIGN KEY (`idAula`)
    REFERENCES `ii_admision_unsa`.`Aula` (`idAula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Area` (
  `idArea` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Ubicacion` VARCHAR(45) NULL DEFAULT NULL,
  `Habilitada` TINYINT(1) NULL DEFAULT NULL,
  `Integrantes` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Curso` (
  `idCurso` INT NOT NULL,
  `Curricula` VARCHAR(45) NULL DEFAULT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Resolucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Resolucion` (
  `idResolucion` INT NOT NULL,
  `Alternativa_correcta` VARCHAR(45) NULL DEFAULT NULL,
  `Sustento` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idResolucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Tipo_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Tipo_Usuario` (
  `idTipo_Usuario` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  `Privilegio` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipo_Usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Usuario` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Contrasenha` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `idTipo_Usuario` INT NOT NULL COMMENT '		',
  `Online` TINYINT(1) NOT NULL,
  INDEX `fk_Usuario_1_idx` (`idTipo_Usuario` ASC),
  PRIMARY KEY (`Nombre`),
  CONSTRAINT `fk_Usuario_1`
    FOREIGN KEY (`idTipo_Usuario`)
    REFERENCES `ii_admision_unsa`.`Tipo_Usuario` (`idTipo_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Tema` (
  `idTema` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`AreaXCursoXTema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`AreaXCursoXTema` (
  `idAreaXCursoXTema` INT NOT NULL,
  `idArea` INT NULL,
  `idCurso` INT NULL,
  `idTema` INT NULL,
  `Anho_inclusión` DATE NULL,
  `Vigente` TINYINT(1) NULL,
  PRIMARY KEY (`idAreaXCursoXTema`),
  INDEX `fk_AreaXCursoXTema_1_idx` (`idArea` ASC),
  INDEX `fk_AreaXCursoXTema_2_idx` (`idCurso` ASC),
  INDEX `fk_AreaXCursoXTema_3_idx` (`idTema` ASC),
  CONSTRAINT `fk_AreaXCursoXTema_1`
    FOREIGN KEY (`idArea`)
    REFERENCES `ii_admision_unsa`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AreaXCursoXTema_2`
    FOREIGN KEY (`idCurso`)
    REFERENCES `ii_admision_unsa`.`Curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AreaXCursoXTema_3`
    FOREIGN KEY (`idTema`)
    REFERENCES `ii_admision_unsa`.`Tema` (`idTema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Pregunta` (
  `idPregunta` INT NOT NULL AUTO_INCREMENT,
  `Elegida` TINYINT(1) NULL DEFAULT NULL,
  `Dificultad` VARCHAR(45) NULL DEFAULT NULL,
  `Inicio_de_pregunta` VARCHAR(45) NULL,
  `Enunciado` VARCHAR(45) NULL DEFAULT NULL,
  `Distractor_A` VARCHAR(45) NULL DEFAULT NULL,
  `Distractor_B` VARCHAR(45) NULL DEFAULT NULL,
  `Distractor_C` VARCHAR(45) NULL,
  `Distractor_D` VARCHAR(45) NULL,
  `Distractor_E` VARCHAR(45) NULL,
  `Fecha` DATETIME NULL,
  `idProceso` INT NULL,
  `DNI` INT NULL,
  `idResolucion` INT NULL,
  `idAreaXCursoXTema` INT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idPregunta`),
  INDEX `fk_Pregunta_1_idx` (`DNI` ASC),
  INDEX `fk_Pregunta_2_idx` (`idProceso` ASC),
  INDEX `fk_Pregunta_4_idx` (`idResolucion` ASC),
  INDEX `fk_Pregunta_5_idx` (`Nombre` ASC),
  INDEX `fk_Pregunta_3_idx` (`idAreaXCursoXTema` ASC),
  CONSTRAINT `fk_Pregunta_1`
    FOREIGN KEY (`DNI`)
    REFERENCES `ii_admision_unsa`.`Participante` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pregunta_2`
    FOREIGN KEY (`idProceso`)
    REFERENCES `ii_admision_unsa`.`Proceso` (`idProceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pregunta_4`
    FOREIGN KEY (`idResolucion`)
    REFERENCES `ii_admision_unsa`.`Resolucion` (`idResolucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pregunta_5`
    FOREIGN KEY (`Nombre`)
    REFERENCES `ii_admision_unsa`.`Usuario` (`idTipo_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pregunta_3`
    FOREIGN KEY (`idAreaXCursoXTema`)
    REFERENCES `ii_admision_unsa`.`AreaXCursoXTema` (`idAreaXCursoXTema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Permisos` (
  `idPermisos` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Valor` INT NOT NULL,
  PRIMARY KEY (`idPermisos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Tipo_Usuario&Permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Tipo_Usuario&Permisos` (
  `idTipo_Usuario&Permisos` INT NOT NULL AUTO_INCREMENT,
  `Vigente` TINYINT(1) NULL DEFAULT NULL,
  `idTipo_Usuario` INT NOT NULL,
  `idPermisos` INT NOT NULL,
  PRIMARY KEY (`idTipo_Usuario&Permisos`),
  INDEX `fk_Tipo_Usuario&Permisos_1_idx` (`idTipo_Usuario` ASC),
  INDEX `fk_Tipo_Usuario&Permisos_2_idx` (`idPermisos` ASC),
  CONSTRAINT `fk_Tipo_Usuario&Permisos_1`
    FOREIGN KEY (`idTipo_Usuario`)
    REFERENCES `ii_admision_unsa`.`Tipo_Usuario` (`idTipo_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tipo_Usuario&Permisos_2`
    FOREIGN KEY (`idPermisos`)
    REFERENCES `ii_admision_unsa`.`Permisos` (`idPermisos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Proceso&Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Proceso&Usuario` (
  `idProceso&Usuario` INT NOT NULL,
  `Comentario` VARCHAR(45) NULL DEFAULT NULL,
  `idProceso` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Actual` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idProceso&Usuario`),
  INDEX `fk_Proceso&Usuario_1_idx` (`idProceso` ASC),
  INDEX `fk_Proceso&Usuario_2_idx` (`Nombre` ASC),
  CONSTRAINT `fk_Proceso&Usuario_1`
    FOREIGN KEY (`idProceso`)
    REFERENCES `ii_admision_unsa`.`Proceso` (`idProceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proceso&Usuario_2`
    FOREIGN KEY (`Nombre`)
    REFERENCES `ii_admision_unsa`.`Usuario` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`ParticipanteXCargo_UNSA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`ParticipanteXCargo_UNSA` (
  `idParticipanteXCargo_UNSA` INT NOT NULL AUTO_INCREMENT,
  `DNI` INT NULL,
  `idCargo_UNSA` INT NULL,
  `Dependencia/Facultad` VARCHAR(45) NULL,
  `Categoria` VARCHAR(45) NULL,
  `Regimen` VARCHAR(45) NULL,
  `Es_cargo_actual` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idParticipanteXCargo_UNSA`),
  INDEX `fk_Participante&Cargo_UNSA_1_idx` (`idCargo_UNSA` ASC),
  INDEX `fk_Participante&Cargo_UNSA_2_idx` (`DNI` ASC),
  CONSTRAINT `fk_ParticipanteXCargo_UNSA_1`
    FOREIGN KEY (`idCargo_UNSA`)
    REFERENCES `ii_admision_unsa`.`Cargo_UNSA` (`idCargo_UNSA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ParticipanteXCargo_UNSA_2`
    FOREIGN KEY (`DNI`)
    REFERENCES `ii_admision_unsa`.`Participante` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`Cargo_ProcesoXCargo_UNSA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`Cargo_ProcesoXCargo_UNSA` (
  `idCargo_ProcesoXCargo_UNSA` INT NOT NULL AUTO_INCREMENT,
  `idCargo_Proceso` INT NULL,
  `idCargo_UNSA` INT NULL,
  `Es_compatible` TINYINT(1) NULL,
  PRIMARY KEY (`idCargo_ProcesoXCargo_UNSA`),
  INDEX `fk_Cargo_Proceso&Cargo_UNSA_2_idx` (`idCargo_UNSA` ASC),
  INDEX `fk_Cargo_ProcesoXCargo_UNSA_1_idx` (`idCargo_Proceso` ASC),
  CONSTRAINT `fk_Cargo_ProcesoXCargo_UNSA_1`
    FOREIGN KEY (`idCargo_Proceso`)
    REFERENCES `ii_admision_unsa`.`Cargo_Proceso` (`idCargo_Proceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cargo_ProcesoXCargo_UNSA_2`
    FOREIGN KEY (`idCargo_UNSA`)
    REFERENCES `ii_admision_unsa`.`Cargo_UNSA` (`idCargo_UNSA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`ProcesoXCargo_ProcesoXArea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`ProcesoXCargo_ProcesoXArea` (
  `idProcesoXCargo_ProcesoXArea` INT NOT NULL,
  `idProceso` INT NULL,
  `idCargo_Proceso` INT NULL,
  `idArea` INT NULL,
  `Cupos` INT NULL,
  `Cant_seleccionados` INT NULL,
  PRIMARY KEY (`idProcesoXCargo_ProcesoXArea`),
  INDEX `fk_Proceso&Cargo_Proceso&Area_2_idx` (`idCargo_Proceso` ASC),
  INDEX `fk_Proceso&Cargo_Proceso&Area_3_idx` (`idArea` ASC),
  INDEX `fk_ProcesoXCargo_ProcesoXArea_1_idx` (`idProceso` ASC),
  CONSTRAINT `fk_ProcesoXCargo_ProcesoXArea_1`
    FOREIGN KEY (`idProceso`)
    REFERENCES `ii_admision_unsa`.`Proceso` (`idProceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProcesoXCargo_ProcesoXArea_2`
    FOREIGN KEY (`idCargo_Proceso`)
    REFERENCES `ii_admision_unsa`.`Cargo_Proceso` (`idCargo_Proceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProcesoXCargo_ProcesoXArea_3`
    FOREIGN KEY (`idArea`)
    REFERENCES `ii_admision_unsa`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`ProcesoXCargo_Proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`ProcesoXCargo_Proceso` (
  `idProcesoXCargo_Proceso` INT NOT NULL,
  `idProceso` INT NULL,
  `idCargo_Proceso` INT NULL,
  `Cupos` INT NULL,
  `Cant_seleccionados` INT NULL,
  PRIMARY KEY (`idProcesoXCargo_Proceso`),
  INDEX `fk_ProcesoXCargo_Proceso_1_idx` (`idProceso` ASC),
  INDEX `fk_ProcesoXCargo_Proceso_2_idx` (`idCargo_Proceso` ASC),
  CONSTRAINT `fk_ProcesoXCargo_Proceso_1`
    FOREIGN KEY (`idProceso`)
    REFERENCES `ii_admision_unsa`.`Proceso` (`idProceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProcesoXCargo_Proceso_2`
    FOREIGN KEY (`idCargo_Proceso`)
    REFERENCES `ii_admision_unsa`.`Cargo_Proceso` (`idCargo_Proceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ii_admision_unsa`.`ProcesoXAreaXCursoXTema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ii_admision_unsa`.`ProcesoXAreaXCursoXTema` (
  `idProcesoXAreaXCursoXTema` INT NOT NULL,
  `idProceso` INT NULL,
  `idAreaXCursoXTema` INT NULL,
  `Nro_hecho_de_preguntas` INT NULL,
  `Nro_total_de_preguntas` INT NULL,
  PRIMARY KEY (`idProcesoXAreaXCursoXTema`),
  INDEX `fk_ProcesoXAreaXCursoXTema_1_idx` (`idProceso` ASC),
  INDEX `fk_ProcesoXAreaXCursoXTema_2_idx` (`idAreaXCursoXTema` ASC),
  CONSTRAINT `fk_ProcesoXAreaXCursoXTema_1`
    FOREIGN KEY (`idProceso`)
    REFERENCES `ii_admision_unsa`.`Proceso` (`idProceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProcesoXAreaXCursoXTema_2`
    FOREIGN KEY (`idAreaXCursoXTema`)
    REFERENCES `ii_admision_unsa`.`AreaXCursoXTema` (`idAreaXCursoXTema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
